### ISSUE TITLE
An accessibility workshop for RSE Asia

### ISSUE THREAD

**Issue by SaranjeetKaur** [isabela-pf/isabela-pf#5]
Hi Isabela,

I'm reaching out to you after I attended the Alt-text workshop that you and Mars recently organized for the Scientific Python community.  I'm the Co-Founder of the [RSE Asia Association](https://rse-asia.github.io/RSE_Asia/) and am looking for a similar workshop to be run for the members of the RSE Asia community.

RSE Asia was launched in 2021 with the motive to promote the research software engineering community & profession in Asia. It is a completely volunteer run organization. We are keen to promote an understanding of accessibility of anything related to research software engineering through our activities. In the same vein, I'm reaching out to you if you would be interested in hosting a workshop for our community. 

We would be happy to work on the Scientific Python blog that you discussed in your previous workshop. I read in your profile that you also work for improving accessibility in the Jupyter communities - do you have any ideas related to it that can be taught to the members of the RSE Asia community? Or if there is some other idea that you might have, then we can discuss on that. Your recent Alt-text workshop was itself very engaging and quite a nice learning experience for me - so if you would be available to teach some of those skills to our community then that would be super helpful! Open to your ideas & to discuss further! 

All best,
Saranjeet
Personal web: https://saranjeetkaur.github.io/About-Me/

**Comment by isabela-pf** [comment]
Hi Saranjeet, thanks for reaching out! I'm happy to hear you felt the workshop was useful and want to bring it to others. I personally love bringing this event to different communities, so I'm sure we can schedule something. Did you have a rough time in mind, or are there any times that would definitely not work to schedule a workshop?

You are correct that I like to focus on accessibility work! There's certainly a lot to learn, so I would want to know what skills you think would benefit the RSE Asia community most. For example, it's always possible to talk about an introduction to accessibility, but it may not be right for an audience who wants more specific guidelines or already knows the foundation.

If you'd rather discuss this off github for any reason, let me know and I'll start an email thread. 🌻 Hope you have a lovely day!

---

Tagging @marsbarlee because she might want to be involved, too!

**Comment by SaranjeetKaur** [comment]
Thank you for your quick response Isabela!

I'm happy to discuss more over email, here is mine:
***@***.*** Very happy to have Mars involved too, if she is
interested!

Let's discuss over email then - could you please drop me a message over
email and we can take it from there?

**Comment by isabela-pf** [comment]
Hi! I'm closing this as we got this sorted and had a lovely event. Thank you again for reaching out and organizing! 🌻
